//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LecturerCourseSubject
    {
        public int id { get; set; }
        public Nullable<int> LecturerID { get; set; }
        public Nullable<int> CourseSubjectID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> isFlagged { get; set; }
    
        public virtual CourseSubject CourseSubject { get; set; }
        public virtual Lecturer Lecturer { get; set; }
    }
}
