//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticalWeight
    {
        public int id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string QuestionBreakDown { get; set; }
        public Nullable<int> practicalQuestionWeight { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
